spring:
  datasource:
    druid:
          biu:
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/biu?characterEncoding=UTF-8&useSSL=false
            initialSize: 5
            minIdle: 5
            maxWait: 60000
            maxActive: 20
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
          bianla:
           username: root
           password: root
           driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://localhost:3306/bianla_qa?characterEncoding=UTF-8&useSSL=false
           initialSize: 5
           minIdle: 5
           maxWait: 60000
           maxActive: 20
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: SELECT 1
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 20
          community:
           username: root
           password: root
           driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://localhost:3306/bianla_community?characterEncoding=UTF-8&useSSL=false
           initialSize: 5
           minIdle: 5
           maxWait: 60000
           maxActive: 20
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: SELECT 1
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 20