db: biu
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  redis:
    host: localhost
    port: 6379
logging:
  path: ./logs
  level:
    com.abc.dao: debug
