server:
  port: 8889
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev #dev,test,prod三种配置一键切换
    include: mybatisplus,shiro
logging:
  path: ./logs
  level:
    com.abc.dao: debug
